# Dockerfile.bot — para main.py en produccion
FROM python:3.12-alpine
WORKDIR /app
RUN apk add --no-cache zbar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ .
CMD ["python", "main.py"]